import postgres from "postgres";
import { drizzle } from "drizzle-orm/postgres-js";
import { inArray } from "drizzle-orm";
import {
  firewallRules,
  ruleTypes,
} from "../src/adapters/outbound/persistence/drizzle/schema";
import { config } from "../src/main/config/env";
import {
  RULE_TYPE_IDS,
  encodeValue,
} from "../src/adapters/outbound/persistence/drizzle/firewallRuleMapper";
import { RuleType } from "../src/domain/models/RuleType";
import { Mode } from "../src/domain/models/FirewallRule";

// The seed targets whichever database the validated config selects, so it can
// never disagree with the URI the application itself uses.
const client = postgres(config.databaseUri, { max: 1 });
const db = drizzle(client);

interface SampleRule {
  type: RuleType;
  value: string | number;
  mode: Mode;
  active?: boolean;
}

/**
 * Example rules, used only by `npm run db:seed:sample`. Add entries here.
 *
 * Every value must be semantically valid for its type or the API would reject
 * the same rule: real IPv4, bare domain (no protocol, path or port), port in
 * 1..65535. The addresses come from the documentation ranges reserved by
 * RFC 5737 and the domains from RFC 2606, so nothing here can ever point at a
 * real host by accident.
 */
const SAMPLE_RULES: readonly SampleRule[] = [
  { type: RuleType.IP, value: "192.0.2.10", mode: "blacklist" },
  { type: RuleType.IP, value: "192.0.2.11", mode: "blacklist", active: false },
  { type: RuleType.IP, value: "198.51.100.25", mode: "whitelist" },
  { type: RuleType.DOMAIN, value: "malware.example", mode: "blacklist" },
  { type: RuleType.DOMAIN, value: "ads.example.net", mode: "blacklist" },
  { type: RuleType.DOMAIN, value: "intranet.example.org", mode: "whitelist" },
  { type: RuleType.PORT, value: 23, mode: "blacklist" },
  { type: RuleType.PORT, value: 445, mode: "blacklist" },
  { type: RuleType.PORT, value: 8080, mode: "whitelist", active: false },
];

async function seedRuleTypes(): Promise<void> {
  // Ids come from the mapper, so the seeded rows and the persistence mapping
  // cannot drift apart. onConflictDoNothing keeps repeated runs idempotent.
  const values = Object.values(RuleType).map((type: RuleType) => ({
    id: RULE_TYPE_IDS[type],
    name: type,
  }));

  await db.insert(ruleTypes).values(values).onConflictDoNothing();

  console.log("Rule types seeded successfully.");
}

/**
 * Idempotent without a unique constraint: firewall_rules.id is generated by
 * PostgreSQL, so there is no key to conflict on. The already present
 * (type_id, value) pairs are read first and only the missing ones inserted,
 * which also leaves any rule the user has since edited untouched.
 */
async function seedSampleRules(): Promise<void> {
  const wanted = SAMPLE_RULES.map((rule) => ({
    typeId: RULE_TYPE_IDS[rule.type],
    value: encodeValue(rule.value),
    mode: rule.mode,
    active: rule.active ?? true,
  }));

  const existing = await db
    .select({ typeId: firewallRules.typeId, value: firewallRules.value })
    .from(firewallRules)
    .where(
      inArray(
        firewallRules.value,
        wanted.map((rule) => rule.value),
      ),
    );

  const present = new Set(existing.map((row) => `${row.typeId}|${row.value}`));
  const missing = wanted.filter(
    (rule) => !present.has(`${rule.typeId}|${rule.value}`),
  );

  if (missing.length === 0) {
    console.log("Sample rules already present, nothing to insert.");
    return;
  }

  await db.insert(firewallRules).values(missing);

  console.log(
    `Sample rules seeded successfully: ${missing.length} inserted, ` +
      `${wanted.length - missing.length} already present.`,
  );
}

/**
 * rule_types is lookup data the firewall_rules foreign key depends on, so it is
 * always seeded. The sample rules are demo content and are opt-in: the Compose
 * `migrate` service runs the plain `db:seed` in production too, and demo rules
 * must never appear there by default.
 */
const withSampleRules =
  process.argv.includes("--with-sample-rules") ||
  process.env.SEED_SAMPLE_RULES === "true";

async function seed(): Promise<void> {
  await seedRuleTypes();

  if (withSampleRules) {
    await seedSampleRules();
  }
}

seed()
  .catch((error) => {
    console.error("Failed to seed the database:", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await client.end();
  });
