import 'dotenv/config';
import { eq } from 'drizzle-orm';
import {
  createDatabase,
  DatabaseHandle,
} from '../../src/adapters/outbound/persistence/drizzle/database';
import { PostgresFirewallRepository } from '../../src/adapters/outbound/persistence/drizzle/PostgresFirewallRepository';
import {
  firewallRules,
  ruleTypes,
} from '../../src/adapters/outbound/persistence/drizzle/schema';
import { RULE_TYPE_IDS } from '../../src/adapters/outbound/persistence/drizzle/firewallRuleMapper';
import { FirewallRuleFactory } from '../../src/application/factories/FirewallRuleFactory';
import { RuleType } from '../../src/domain/models/RuleType';
import { describeFirewallRepositoryContract } from '../fixtures/firewallRepositoryContract';

/**
 * Integration tests against a real PostgreSQL instance — nothing here falls
 * back to memory. Point them at a database with:
 *
 *   docker compose up -d
 *   npm run db:migrate
 *   npm run db:seed
 *
 * TEST_DATABASE_URI overrides the target; otherwise DEV_DATABASE_URI is used.
 */
const databaseUri = process.env.TEST_DATABASE_URI ?? process.env.DEV_DATABASE_URI;

jest.setTimeout(30000);

let handle: DatabaseHandle;
const factory = new FirewallRuleFactory();

/** Fails loudly rather than silently degrading when no database is reachable. */
async function connectOrExplain(): Promise<void> {
  if (!databaseUri) {
    throw new Error(
      'No database URI configured. Set TEST_DATABASE_URI or DEV_DATABASE_URI in .env.',
    );
  }

  handle = createDatabase(databaseUri);

  try {
    // A single probe, not the Stop-and-Wait loop, which would never return.
    await handle.client`SELECT 1`;
  } catch (error) {
    await handle.close().catch(() => undefined);
    throw new Error(
      `PostgreSQL is not reachable at ${databaseUri}. Start it with "docker compose up -d" ` +
        `and apply migrations with "npm run db:migrate". Original error: ${String(error)}`,
    );
  }

  // The firewall_rules.type_id foreign key needs these rows; seeding here keeps
  // the suite runnable against a freshly migrated database.
  await handle.db
    .insert(ruleTypes)
    .values(
      Object.values(RuleType).map((type: RuleType) => ({
        id: RULE_TYPE_IDS[type],
        name: type,
      })),
    )
    .onConflictDoNothing();
}

describeFirewallRepositoryContract('PostgresFirewallRepository', {
  createRepository: () => new PostgresFirewallRepository(handle.db, factory),
  setUp: connectOrExplain,
  tearDown: async () => {
    await handle.close();
  },
});

describe('PostgresFirewallRepository PostgreSQL specifics', () => {
  let repository: PostgresFirewallRepository;
  const createdIds: number[] = [];

  beforeAll(async () => {
    await connectOrExplain();
    repository = new PostgresFirewallRepository(handle.db, factory);
  });

  afterAll(async () => {
    for (const id of createdIds) {
      await handle.db.delete(firewallRules).where(eq(firewallRules.id, id));
    }
    await handle.close();
  });

  /** Creates a rule and schedules the row for deletion. */
  async function create(type: RuleType, value: string | number) {
    const rule = await repository.create(type, value, true, 'blacklist');
    createdIds.push(rule.id);

    return rule;
  }

  describe('identity ownership', () => {
    it('returns an id generated by PostgreSQL, not by the application', async () => {
      // Arrange & Act
      const rule = await create(RuleType.IP, '10.30.0.1');

      // Assert: the row carrying that id exists in the database itself.
      const rows = await handle.db
        .select()
        .from(firewallRules)
        .where(eq(firewallRules.id, rule.id));

      expect(rows).toHaveLength(1);
      expect(rows[0]!.id).toBe(rule.id);
    });

    it('keeps assigning fresh ids across separate repository instances', async () => {
      // Arrange
      const first = await create(RuleType.IP, '10.30.0.2');
      const other = new PostgresFirewallRepository(handle.db, factory);

      // Act
      const second = await other.create(RuleType.IP, '10.30.0.3', true, 'blacklist');
      createdIds.push(second.id);

      // Assert
      expect(second.id).not.toBe(first.id);
    });
  });

  describe('row mapping', () => {
    it('stores the rule type as its seeded type_id', async () => {
      // Arrange
      const rule = await create(RuleType.DOMAIN, 'mapping.example.com');

      // Act
      const rows = await handle.db
        .select()
        .from(firewallRules)
        .where(eq(firewallRules.id, rule.id));

      // Assert
      expect(rows[0]!.typeId).toBe(RULE_TYPE_IDS[RuleType.DOMAIN]);
    });

    it('stores a port as text but hands it back as a number', async () => {
      // Arrange
      const rule = await create(RuleType.PORT, 9443);

      // Act
      const rows = await handle.db
        .select()
        .from(firewallRules)
        .where(eq(firewallRules.id, rule.id));
      const readBack = await repository.getById(rule.id);

      // Assert
      expect(rows[0]!.value).toBe('9443');
      expect(readBack!.value).toBe(9443);
      expect(typeof readBack!.value).toBe('number');
    });

    it('persists the mode enum', async () => {
      // Arrange
      const rule = await repository.create(RuleType.IP, '10.30.0.4', true, 'whitelist');
      createdIds.push(rule.id);

      // Act
      const rows = await handle.db
        .select()
        .from(firewallRules)
        .where(eq(firewallRules.id, rule.id));

      // Assert
      expect(rows[0]!.mode).toBe('whitelist');
    });

    it('defaults nothing silently: the active flag round-trips as given', async () => {
      // Arrange
      const rule = await repository.create(RuleType.IP, '10.30.0.5', false, 'blacklist');
      createdIds.push(rule.id);

      // Act
      const readBack = await repository.getById(rule.id);

      // Assert
      expect(readBack!.active).toBe(false);
    });
  });

  describe('durability', () => {
    it('keeps data available to a completely new repository instance', async () => {
      // Arrange
      const rule = await create(RuleType.IP, '10.30.0.6');

      // Act: a fresh repository over the same database, as a restart would build.
      const rebuilt = new PostgresFirewallRepository(handle.db, factory);
      const found = await rebuilt.getById(rule.id);

      // Assert
      expect(found).toBeDefined();
      expect(found!.value).toBe('10.30.0.6');
    });

    it('survives a brand new client and connection', async () => {
      // Arrange
      const rule = await create(RuleType.PORT, 9444);

      // Act: a separate connection proves the data is in PostgreSQL, not memory.
      const separate = createDatabase(databaseUri!);
      try {
        const found = await new PostgresFirewallRepository(
          separate.db,
          factory,
        ).getById(rule.id);

        // Assert
        expect(found).toBeDefined();
        expect(found!.value).toBe(9444);
      } finally {
        await separate.close();
      }
    });
  });
});
